
pair: ["bybit", "BTCUSDT"]

# Format: [EntryBPS, ExitBPS, QuoteSize]
# Remember your fees when chosing levels!
stink_levels: [
  [225, 100, 30000], 
  [225, 100, 30000], 
  [175, 100, 20000], 
  [125, 75, 10000], 
  [75, 50, 7500] 
]
