
bybit:
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

binance: 
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

hyperliquid:
  key: "twitter.com/beatzxbt"     # NOTE: This is your wallet address
  secret: "twitter.com/beatzxbt"  # NOTE: Assosiated private key

okx: 
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

kucoin: 
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"
    