
bybit:
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

binance: 
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

okx: 
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

kucoin: 
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"

hyperliquid: # NOTE: key = address, secret = private key
  key: "twitter.com/beatzxbt"
  secret: "twitter.com/beatzxbt"
    