[binance_symbol]
    [binance_symbol.default]
        symbol = "XMRUSDT"
        tick_size = 0.01
        lot_size = 0.01
    [binance_symbol.btc]
        symbol = "BTCUSDT"
        tick_size = 0.01
        lot_size = 0.05

[bybit_symbol]
    [bybit_symbol.default]
        symbol = "XMRUSDT"
        tick_size = 0.05
        lot_size = 0.01
    [bybit_symbol.btc]
        symbol = "BTCUSDT"
        tick_size = 0.01
        lot_size = 0.01


# Primary data feed (BYBIT or BINANCE) 
# Check README.md for more info regarding this 
[data_feed]
    [data_feed.default]
        feed = "BINANCE"
    [data_feed.bybit]
        feed = "BYBIT"

# A multiple of the tick size
# Prevents a 'ping-pong' effect
[buffer]
    [buffer.default]
        buffer = 3

[account]
    [account.default]
        size = 100
    [account.arb]
        size = 1000

# Settings for volatility indicator 
[volatility]
    [volatility.default]
        bollinger_band_length = 20
        bollinger_band_std = 5

[offsets]
    [offsets.default]
        quote_offset = 0
        size_offset = 0
        volatility_offset = 0

# The 'strategies' section contains configurations for various trading strategies.
[strategies]
    [strategies.marketmaker]
        [strategies.marketmaker.default]
            base_spread = 0.1
            number_of_orders = 10
            min_order_size = 0.1
            max_order_size = 0.45
        [strategies.marketmaker.safe]
            base_spread = 0.1
            number_of_orders = 5
            min_order_size = 0.05
            max_order_size = 0.15
    [strategies.arbitrage]
        [strategies.arbitrage.default]
            bull = 0.1

# The 'strategy' section specifies the active trading strategy to be used.
[strategy]
    [strategy.default]
        strategy = "marketmaker"
    [strategy.arbitrage]
        strategy = "arbitrage"