
symbols: [
  ["BINANCE", "XMRUSDT"], 
  ["BYBIT", "XMRUSDT"]
]

# Settings for volatility indicator 
bollinger_band_length: 20
bollinger_band_std: 5

# Master offsets
quote_offset: 0.0 # Changes quote price in base units
size_offset: 0.0  # Changes quote size in quote units
volatility_offset: 0.0 # Changes quote range in base units

strategies:
  
  base_spread: 0.1 # In quote asset unit
  min_order_size: 0.1  # In base asset unit
  max_order_size: 0.45  # In base asset unit
