
primary_exchange: "bybit"

pairs: [
  ["binance", "XMRUSDT"], 
  ["bybit", "XMRUSDT"]
]

quote_generator: "simple" # Choices: "simple", "basic" ,..., etc

parameters:
  basic:
    base_spread: 0.1 
    min_order_size: 0.1  
    max_order_size: 0.45  

  simple:
    base_spread: 0.1 
    min_order_size: 0.1  
    max_order_size: 0.45  
