#[api_key] is the default api_key, it will use it as a default or when you use -k 1
[api_key]
api_key = "twitter.com/@beatzxbt"
api_secret = "twitter.com/@beatzxbt"

[api_key_2]
api_key = "twitter.com/@lev"
api_secret = "twitter.com/@beatzxbt"

#You can use names for keys too like algo or anything else
[api_key_algo]
api_key = "twitter.com/lev"
api_secret = "twitter.com/@beatzxbt"
