[binance_symbol]

symbol = "XMRUSDT"
tick_size = 0.01
lot_size = 0.01

[bybit_symbol]

symbol = "XMRUSDT"
tick_size = 0.05
lot_size = 0.01

#For others symbols you use a name 
#WARNING: IF YOU USE ANOTHER SYMBOL YOU SHOULD MAKE A BYBIT SYMBOL FOR IT TOO
#-t/--ticker btc
[binance_symbol_btc]

symbol = "BTCUSDT"
tick_size = 0.01
lot_size = 0.01

[bybit_symbol_btc]

symbol = "BTCUSDT"
tick_size = 0.01
lot_size = 0.01


# Primary data feed (BYBIT or BINANCE) 
# Check README.md for more info regarding this 
[data_feed]
primary = "BINANCE"

# A multiple of the tick size
# Prevents a 'ping-pong' effect
[buffer]
value = 3